### ISSUE TITLE
Use of linkDescriptor

### ISSUE THREAD

**Issue by KoenWindey** [hilch/Pvi.py#5]
Hi Christoph,

Forgive me if I'm asking silly questions, I'm starting to puzzle things together of how PVI Manager works. It takes a lot of reading of the PVI manual and your examples, and trial and error.

One thing that is playing on my mind is how in PviPy, there seems to be no space to define the linkDescriptor. As I understand it, the objectDescriptor defines how PVI Manager interacts with the external PLC, while the linkDescriptor defines how the application interacts with PVI Manager.

Looking through the various modules, I can see a linkDescriptor is needed to use PviLink or PviCreate (from pvi_h.py). Only PviCreate seems to be used (Object.py). And then the linkDescriptor is specifically set to "EV=ep", but only for CPU or MODULE objects. I know "EV" defaults to 'ed', which seems sufficient in most cases - but there may be cases for a different setting. 

Maybe a better example would be if I want to use variable addressing (VA parameter), to obtain eg. an element of an array - I would also need to have access to the linkDescriptor?

To make this happen, I would assume changes are needed to the Variable Class to include a linkDescriptor, and then pass it to the parent object and eventually the connection ?

Regards
Koen

**Comment by hilch** [comment]
Hi Koen,

you are absolute right. A complete implementation would need to enable changing the link descriptor, too.
And yes, in this case we would need to change the constructor for Variable class as you described already.

However, it would also be desirable to change the link descriptor for the runtime, e.g. changing some variables from 'active' to 'passive' if they are not used for some time.

**Comment by hilch** [comment]
Hi Koen,

89e2f66f92c7798fcfec5cc84653a19dea85b72d

- 'EV' in objectdescriptor enables to set the event mask when creating the object
- Object.evmask does the same during runtime.

**Comment by KoenWindey** [comment]
Hi Christoph,

The EV parameter for the link descriptor would work the way you are proposing it, although it's a shame it has to be passed through the object descriptor.

However, I am still no quite clear how to do Variable Addressing ([https://help.br-automation.com/#/en/4/automationnet/pvibase/core/pviprocessdataaddressing.htm](https://help.br-automation.com/#/en/4/automationnet/pvibase/core/pviprocessdataaddressing.htm)). Putting the 'AV' parameter in the Object Descriptor doesn't really help, and as pointed out in the manual, for Variable Addressing you also need to pass a type in the lik descriptor.

Would it be worth implementing an actual link descriptor in the Variable Class (eg. `def __init__(self, parent: PviObject, name: str, **objectDescriptor, **linkDescriptor`)?

**Comment by hilch** [comment]
Hi Koen,

> The EV parameter for the link descriptor would work the way you are proposing it, although it's a shame it has to be passed through the object descriptor.

I agree that is not complete clean :-(. It is a way to keep the constructor compatible since 'EV' is not used in object descriptor.
Then we have to find another way...

> However, I am still no quite clear how to do Variable Addressing (https://help.br-automation.com/#/en/4/automationnet/pvibase/core/pviprocessdataaddressing.htm). Putting the 'AV' parameter in the Object Descriptor doesn't really help, and as pointed out in the manual, for Variable Addressing you also need to pass a type in the lik descriptor.

I never used that (I never needed that). But it is 'VA' not 'AV'. I think bit and field addressing can be done easier with Python itself. Since it is just the link what takes this job we do not even reduce network load. But yep: currently one is not able to put it in the link descriptor.

> Would it be worth implementing an actual link descriptor in the Variable Class (eg. def __init__(self, parent: PviObject, name: str, **objectDescriptor, **linkDescriptor)?

Unfortunately Python doesn’t allow passing multiple separate sets of keyword arguments
And the linkDescriptor should be available in all objects.

Best Regards,
Christoph

**Comment by hilch** [comment]
Hi @KoenWindey ,

would you prefer this syntax:

temperature = Variable( task1, name='myTemp', CD = '/RO=gHeating.status.actTemp', RF=2000 , Link='EV=eds' )

Best Regards,
Christoph

**Comment by hilch** [comment]
Hi Koen,

I now implemented it in this way : c75809a8e0633ae00ba8179683e64fc445357e33

So this is possible now:

temperature = Variable( task1, name='myTemp', CD = '/RO=gHeating.status.actTemp', RF=2000 , LinkDescriptor='EV=eds' )

or 

temperature = Variable( task1, name='myTemp', CD = '/RO=gHeating.status.actTemp', RF=2000 , LinkDescriptor={"EV":"eds"} )

Since some parameters work both in the object description and in the link description, we can specify both separately.

**Comment by hilch** [comment]
completed by 1.2.0
