### ISSUE TITLE
Callback instead of polling PVI Manager

### ISSUE THREAD

**Issue by KoenWindey** [hilch/Pvi.py#6]
Hi Christoph,

Am I correct in understanding that at this point Pvi.py only uses User Messages of type 'PVIFUNCTION'? If that's the case, does that mean that we can only get data from PVI Manager by cyclically calling (polling) PVI Manager - by using Connection.doEvents() in a loop or by using Connection.start()?

At the same time, it seems you're using only the synchronous function 'PviRead' and not its asynchronous version 'PviReadResponse'. 

I am concerned that the combination of both polling and synchronous calls may start to cause delays in receiving data if I use a lot of variables from a remote PVI. 

It would mean that time-sensitive data with a fast refresh rate (eg. alarms that are critical for diagnosing) may be received with a significant delay from PVI Manager. And since PVI Manager does not offer timestamps with the data, the delay would impact on the data timestamp assigned by the Python application. I haven't done any tests yet, so I don't know how bad it could get.

I was wondering what your thoughts were on this? 

Kind regards
Koen

**Comment by hilch** [comment]
Hi Koen,
> Am I correct in ...

yes, either Connection.start() or Connection.doEvents() is required to distribute the results. The latter one can be called in a loop defined by your application e.g. when using a GUI

> At the same time ...

for reading the variables I use the events, so PviRead or PviReadRequest is not necessary. The writing is done with the synchronous PviWrite() since all write action to basic variables should not consume to much time.

> It would mean that time-sensitive data ...

Well, PVI is not made for time-critical actions anyway. Refresh times under 50 ms are ignored, for example. And using Python won't make it any better.

I still have to think seriously about temporarily deactivating variables (your other question). That would really make a lot of sense in this case. However, I don't want to lose simplicity either.

**Comment by KoenWindey** [comment]
Hi Christoph,

I read your answer at least 10 times and did some more testing. I understand now that by using the valueChanged callback function, the data is reported by PVI on an event basis. Only the handling of the reported results is in a cyclical loop and checking with PVI Manager based on the PviGetNextResponse. That's much better than what my misunderstanding was before.

As far as the cyclical polling of PVI manager, that doesn't bother me too much. I put the PVI code in a separate thread and any data coming through can be pushed to the rest of the program in a queue. 

You're correct about suitability for time critical applications - I'm not planning to do anything time critical, although it would be interesting how much data we could achieve until there are too many events and datapoints coming in to handle. I guess that will depend as much on the hardware and the connection to the PLC as it does on polling of PVI Manager. In fact, I'm planning on using PVI with remote connection - I can imagine that might cause a bottle neck too.

I'm happy to close this issue.
